name = "emblem-engine"
main = "src/index.ts"
compatibility_date = "2026-01-01"

# Crucial for Photon/Wasm on Cloudflare
[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

[vars]
GW2_API_BASE = "https://api.guildwars2.com/v2"

[[kv_namespaces]]
binding = "EMBLEM_ENGINE_GUILD_LOOKUP"
# This is the ID of the KV namespace. It is not a secret and is safe to commit.
id = "24797f12df1d4f8197edadc01d10535c"

[[r2_buckets]]
binding = "EMBLEM_ASSETS"
bucket_name = "emblem-assets-dev"

